export default {
  FETCH_LIST: 'FETCH_LIST',
  ADD_ITEM: 'ADD_ITEM',
  MOVE_TO_TRASH: 'MOVE_TO_TRASH',
  REVERT_ITEM: 'REVERT_ITEM',
  UPDATE_ITEM: 'UPDATE_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  DELETE_ALL_ITEM: 'DELETE_ALL_ITEM',
  LOGIN: 'LOGIN',
  AUTO_LOGIN: 'AUTO_LOGIN',
  LOGOUT: 'LOGOUT',
};
